workflows:
  android-release-workflow:
    name: Android Release Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      android:
        gradle: true
    scripts:
      - name: Clean project
        script: ./gradlew clean
      - name: Build release APK
        script: ./gradlew assembleRelease
    artifacts:
      - build/app/outputs/apk/release/app-release.apk
    publishing:
      # Saves the APK for download in Codemagic
      artifacts: true
