name: botsguied
description: A modern Botswana Guide app (offline + online with Firebase Firestore)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  animations: ^2.0.11
  lottie: ^3.1.0

  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.5.0
  firebase_messaging: ^15.2.0

  # State management & storage
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Network & location
  connectivity_plus: ^6.1.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.6.0

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
