name: botsguied
description: A modern Botswana Guide app (offline + online with Firebase Firestore)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  firebase_core: ^3.3.0
  cloud_firestore: ^5.4.2
  firebase_auth: ^5.2.1
  firebase_messaging: ^15.1.2
  provider: ^6.1.2
  connectivity_plus: ^6.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  animations: ^2.0.8
  lottie: ^3.1.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
